"""
WildEcho Gemma 2 Ecological Reasoning Engine
Translates detected acoustic fingerprints and microclimate context into
eyes-free whisper briefings and foraging field intelligence.
"""

import httpx
from pydantic import BaseModel

from wildecho.bioacoustics.catalog import SpeciesSignature
from wildecho.config import settings
from wildecho.intelligence.naturalist_prompts import build_gemma_naturalist_prompt


class NaturalistFieldReport(BaseModel):
    """Structured eyes-free field note generated by Gemma 2."""

    species: SpeciesSignature
    confidence: float
    whisper_script: str
    ecological_context: str
    foraging_tip: str
    safety_alert: str | None = None
    generated_by: str = "gemma-2-2b-edge"


class GemmaEcologicalEngine:
    """Offline ecological reasoner using Google Gemma 2."""

    def __init__(
        self,
        model_name: str = settings.gemma_model,
        ollama_endpoint: str = settings.ollama_endpoint,
        timeout_seconds: float = 2.5,
    ):
        self.model_name = model_name
        self.ollama_endpoint = ollama_endpoint
        self.timeout_seconds = timeout_seconds

    def generate_report(
        self,
        species: SpeciesSignature,
        confidence: float,
        ndsi: float,
        aci: float,
        habitat: str = "dense_forest",
        season: str = "autumn",
    ) -> NaturalistFieldReport:
        """
        Generates a naturalist field briefing.
        Attempts local Ollama Gemma 2 inference first; falls back seamlessly to
        embedded deterministic edge synthesis for 100% offline backcountry reliability.
        """
        # Try local Ollama inference if running
        report = self._try_ollama_gemma(species, confidence, ndsi, aci, habitat, season)
        if report:
            return report

        # High-fidelity embedded edge synthesis
        return self._generate_edge_fallback(species, confidence, ndsi, aci, habitat, season)

    def _try_ollama_gemma(
        self, species: SpeciesSignature, confidence: float, ndsi: float, aci: float, habitat: str, season: str
    ) -> NaturalistFieldReport | None:
        """Attempts connection to local Ollama runner hosting Gemma 2."""
        prompt = build_gemma_naturalist_prompt(species, confidence, ndsi, aci, habitat, season)
        try:
            with httpx.Client(timeout=self.timeout_seconds) as client:
                res = client.post(
                    f"{self.ollama_endpoint}/api/generate",
                    json={
                        "model": "gemma2:2b",
                        "prompt": prompt,
                        "stream": False,
                        "options": {"temperature": 0.3, "num_predict": 120},
                    },
                )
                if res.status_code == 200:
                    text = res.json().get("response", "")
                    return self._parse_gemma_output(text, species, confidence)
        except (httpx.HTTPError, ValueError, KeyError, OSError):
            # Fall back silently to offline edge engine
            return None
        return None

    def _parse_gemma_output(self, text: str, species: SpeciesSignature, confidence: float) -> NaturalistFieldReport:
        """Parses structured Gemma output tokens."""
        whisper = f"That call in the canopy is a {species.common_name}. {species.field_description}"
        insight = f"Indicates healthy {species.habitats[0].replace('_', ' ')} habitat."
        foraging = species.foraging_association
        safety = species.safety_note

        for line in text.strip().splitlines():
            line = line.strip()
            if line.startswith("WHISPER:"):
                whisper = line.replace("WHISPER:", "").strip()
            elif line.startswith("INSIGHT:"):
                insight = line.replace("INSIGHT:", "").strip()
            elif line.startswith("FORAGING_SAFETY:"):
                foraging = line.replace("FORAGING_SAFETY:", "").strip()

        return NaturalistFieldReport(
            species=species,
            confidence=confidence,
            whisper_script=whisper,
            ecological_context=insight,
            foraging_tip=foraging,
            safety_alert=safety,
            generated_by=f"{self.model_name}:ollama",
        )

    def _generate_edge_fallback(
        self, species: SpeciesSignature, confidence: float, ndsi: float, aci: float, habitat: str, season: str
    ) -> NaturalistFieldReport:
        """
        Deterministic, embedded edge naturalist synthesis.
        Guarantees zero-network offline functionality deep in wilderness zones.
        """
        # Tailor whisper by species category
        if species.category == "bird":
            whisper = (
                f"Listen to the canopy. That {species.call_pattern.replace('_', ' ')} is a {species.common_name}. "
                f"Take a breath and enjoy the moment."
            )
        elif species.category == "amphibian":
            whisper = (
                f"Hear that resonant rhythm near the water? A {species.common_name} is calling from the bank. "
                f"You're in prime moisture zone."
            )
        elif species.category == "mammal":
            whisper = (
                f"Alert: {species.common_name} vocalization detected nearby. "
                f"Slow your pace, scan the tree line, and stay mindful."
            )
        else:
            whisper = (
                f"The steady chorus above is the {species.common_name}. "
                f"Summer and autumn sounds are in full bloom here."
            )

        # Ecological insight from habitat and NDSI
        if ndsi >= 0.5:
            insight = (
                f"The pristine +{ndsi:.2f} biophony score and {species.common_name} activity "
                f"confirm this {habitat.replace('_', ' ')} stand has minimal human fragmentation."
            )
        else:
            insight = (
                f"Active {species.common_name} singing suggests this trail edge remains "
                f"an important wildlife acoustic corridor despite nearby human noise."
            )

        return NaturalistFieldReport(
            species=species,
            confidence=confidence,
            whisper_script=whisper,
            ecological_context=insight,
            foraging_tip=species.foraging_association,
            safety_alert=species.safety_note,
            generated_by=f"{self.model_name}:offline-edge",
        )
